create schema if not exists kds;

create table kds.stations (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references platform.tenants(id),
  location_id uuid references platform.locations(id),
  station_key text not null,
  name text not null,
  status text not null default 'active'
    check (status in ('active', 'disabled', 'archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, location_id, station_key)
);

create table kds.tickets (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references platform.tenants(id),
  location_id uuid references platform.locations(id),
  order_id uuid not null references commerce.orders(id) on delete cascade,
  contact_id uuid references platform.contacts(id),
  source_channel text not null default 'conversaflow',
  customer_name text,
  customer_phone text,
  pickup_person text,
  status text not null
    check (status in ('new', 'accepted', 'preparing', 'ready', 'completed', 'cancelled', 'partial_cancelled')),
  station_id uuid references kds.stations(id),
  customer_note text,
  cancellation_reason text,
  partial_cancellation_reason text,
  total_cents integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  last_event_sequence bigint,
  last_projected_at timestamptz not null default now(),
  unique (order_id)
);

create index kds_tickets_tenant_status_created_idx
  on kds.tickets (tenant_id, status, created_at);

create table kds.ticket_items (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references platform.tenants(id),
  ticket_id uuid not null references kds.tickets(id) on delete cascade,
  order_item_id uuid references commerce.order_items(id) on delete set null,
  display_order integer not null,
  name text not null,
  quantity integer not null check (quantity > 0),
  variant_name text,
  notes text,
  unit_price_cents integer,
  is_cancelled boolean not null default false,
  unique (ticket_id, display_order)
);

create index kds_ticket_items_ticket_idx
  on kds.ticket_items (ticket_id, display_order);

create table kds.ticket_events (
  sequence bigint generated by default as identity primary key,
  tenant_id uuid not null references platform.tenants(id),
  ticket_id uuid not null references kds.tickets(id) on delete cascade,
  order_id uuid not null references commerce.orders(id) on delete cascade,
  kind text not null
    check (kind in ('snapshot_reconciled', 'order_upserted', 'status_changed', 'order_removed', 'device_action')),
  status text,
  occurred_at timestamptz not null default now(),
  source text not null default 'projection',
  source_event_key text unique,
  payload jsonb not null default '{}'::jsonb
);

create index kds_ticket_events_tenant_sequence_idx
  on kds.ticket_events (tenant_id, sequence);

create table kds.device_sessions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references platform.tenants(id),
  location_id uuid references platform.locations(id),
  station_id uuid references kds.stations(id),
  device_name text not null,
  token_hash text,
  is_active boolean not null default true,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_by uuid,
  revocation_reason text
);

create index kds_device_sessions_tenant_active_idx
  on kds.device_sessions (tenant_id, is_active, last_seen_at desc);

create index kds_device_sessions_revoked_idx
  on kds.device_sessions (tenant_id, location_id, revoked_at desc)
  where revoked_at is not null;

create table kds.device_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references platform.tenants(id),
  device_session_id uuid references kds.device_sessions(id) on delete set null,
  station_id uuid references kds.stations(id),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index kds_device_events_tenant_time_idx
  on kds.device_events (tenant_id, occurred_at desc);

grant select on all tables in schema kds to umi_app, umi_worker, umi_readonly;
