-- Migration 20260613000011_migration_conventions_concurrently.sql
-- #13: CREATE INDEX CONCURRENTLY must run OUTSIDE a transaction.
-- PostgreSQL does not allow CONCURRENTLY inside BEGIN/COMMIT blocks.
--
-- Future migrations that add unique indexes should:
-- 1. NOT wrap the CONCURRENTLY statement in BEGIN/COMMIT
-- 2. Be a standalone migration file (one index per file is safest)
-- 3. Be applied via supabase db push (which handles non-transactional DDL)
-- 4. If applied via supabase db query --linked, remove any BEGIN/COMMIT wrapper
--
-- Example of a SAFE concurrent index migration:
--
--   CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS my_index
--     ON my_table (my_column)
--     WHERE my_column IS NOT NULL;
--
-- This migration is documentation only — no DDL changes.
