-- Migration 20260613000010_cross_tenant_non_goal.sql
-- #9: Cross-tenant identity is intentionally unsupported.
-- The identity graph is per-tenant. A diner at Kalala and El Gran Ribera
-- is two separate people rows with two different tenant_ids.
-- This is a privacy/data-ownership boundary between independent restaurants.
--
-- The only cross-tenant thread is lead→owner→diner for the same business
-- owner, routed through platform.leads.converted_* bridges + platform.users,
-- never through platform.people.
--
-- This migration exists to explicitly document the non-goal so future
-- developers don't try to add cross-tenant merging without understanding
-- the privacy and business-boundary implications.
--
-- No DDL changes — this is a documentation migration.

-- If cross-tenant identity is ever needed, the correct model is:
-- 1. platform.identity_subjects — optional global subject keyed on
--    verified/consented identifiers, independent of tenant
-- 2. platform.person_subject_links — tenant people linked to global subjects
--    with consent, provenance, and confidence
-- 3. Never auto-merge cross-tenant. Privacy implications, phone recycling,
--    and consent requirements make this a product decision, not a DB one.
