-- GENERATED FROM config/umipos-pilot-role-grants.json.
-- Run: pnpm umi-pos:generate-pilot-rbac
-- Do not edit this file by hand.
\set ON_ERROR_STOP on

begin;

-- A clean build-v3 has no legacy backfill. Seed the reviewed business permissions used here.
insert into umi.permission(key,description)
values
  ('insights.read','Read merchant operational insights'),
  ('merchant.manage','Manage one merchant business profile'),
  ('cash.movement.paid_in.approve','Approve a Paid In movement above the active policy threshold'),
  ('cash.movement.paid_out.approve','Approve a Paid Out movement above the active policy threshold'),
  ('cash.movement.safe_drop.approve','Approve a Safe Drop movement above the active policy threshold'),
  ('cash.shift.close.approve','Approve a shift close above the active policy threshold')
on conflict(key) do update set description=excluded.description;

insert into umi.role(key,name,description,is_platform)
values
  ('admin','Administrator','Admin manages one merchant. POS actions still require a trusted device and an operator session.',false),
  ('cashier','Cashier','Cashier completes one assigned shift and requests approval for sensitive actions.',false),
  ('manager','Manager','Manager resolves sensitive operations in explicitly assigned locations.',false),
  ('owner','Owner','Owner is the highest business profile for one merchant. Owner never receives platform authority.',false),
  ('staff','Staff','Staff preserves the current front-of-house authorization model as a Cashier compatibility profile.',false),
  ('super_admin','Super Admin','super_admin remains outside the café grant matrix. The platform seed grants explicit catalog rows.',true),
  ('supervisor','Supervisor','Supervisor approves policy-limited operations in one assigned location.',false),
  ('viewer','Viewer','Viewer receives explicit read access and no mutation permission.',false)
on conflict(key) do update set
  name=excluded.name,
  description=excluded.description,
  is_platform=excluded.is_platform;

-- Reconcile only the reviewed UmiPOS permission vocabulary.
delete from umi.role_permission rp
using umi.role r, umi.permission p
where rp.role_id=r.id
  and rp.permission_id=p.id
  and r.key in ('admin','cashier','manager','owner','staff','supervisor','viewer')
  and p.key in ('audit.read','cart.write','cash.count.recount','cash.count.submit','cash.drawer.no_sale','cash.movement.paid_in','cash.movement.paid_in.approve','cash.movement.paid_out','cash.movement.paid_out.approve','cash.movement.safe_drop','cash.movement.safe_drop.approve','cash.reconcile','cash.register.use','cash.shift.close','cash.shift.close.approve','cash.shift.handoff','cash.shift.open','cash.shift.read','cash.shift.resume','cash.shift.suspend','cash.variance.approve','catalog.read','checkout.commit','checkout.discount.apply','checkout.discount.approve','checkout.recover.any','checkout.terminal.approve','checkout.terminal.confirm','device.enroll','insights.read','merchant.manage','offline.cash.checkout','offline.recovery.review','offline.replay','sale.exception.history','sale.exception.read','sale.lifecycle','sale.refund.approve','sale.refund.cash','sale.refund.full','sale.refund.manual_terminal','sale.refund.other_location','sale.refund.other_operator','sale.refund.partial','sale.refund.reconcile','sale.resume.any','sale.void.create');

with grants(role_key,permission_key) as (
  values
  ('admin','audit.read'),
  ('admin','cart.write'),
  ('admin','cash.count.recount'),
  ('admin','cash.count.submit'),
  ('admin','cash.drawer.no_sale'),
  ('admin','cash.movement.paid_in'),
  ('admin','cash.movement.paid_in.approve'),
  ('admin','cash.movement.paid_out'),
  ('admin','cash.movement.paid_out.approve'),
  ('admin','cash.movement.safe_drop'),
  ('admin','cash.movement.safe_drop.approve'),
  ('admin','cash.reconcile'),
  ('admin','cash.register.use'),
  ('admin','cash.shift.close'),
  ('admin','cash.shift.close.approve'),
  ('admin','cash.shift.handoff'),
  ('admin','cash.shift.open'),
  ('admin','cash.shift.read'),
  ('admin','cash.shift.resume'),
  ('admin','cash.shift.suspend'),
  ('admin','cash.variance.approve'),
  ('admin','catalog.read'),
  ('admin','checkout.commit'),
  ('admin','checkout.discount.apply'),
  ('admin','checkout.discount.approve'),
  ('admin','checkout.recover.any'),
  ('admin','checkout.terminal.approve'),
  ('admin','checkout.terminal.confirm'),
  ('admin','device.enroll'),
  ('admin','insights.read'),
  ('admin','merchant.manage'),
  ('admin','offline.cash.checkout'),
  ('admin','offline.recovery.review'),
  ('admin','offline.replay'),
  ('admin','sale.exception.history'),
  ('admin','sale.exception.read'),
  ('admin','sale.lifecycle'),
  ('admin','sale.refund.approve'),
  ('admin','sale.refund.cash'),
  ('admin','sale.refund.full'),
  ('admin','sale.refund.manual_terminal'),
  ('admin','sale.refund.other_operator'),
  ('admin','sale.refund.partial'),
  ('admin','sale.refund.reconcile'),
  ('admin','sale.resume.any'),
  ('admin','sale.void.create'),
  ('cashier','cart.write'),
  ('cashier','cash.count.submit'),
  ('cashier','cash.movement.paid_in'),
  ('cashier','cash.movement.paid_out'),
  ('cashier','cash.movement.safe_drop'),
  ('cashier','cash.reconcile'),
  ('cashier','cash.register.use'),
  ('cashier','cash.shift.close'),
  ('cashier','cash.shift.open'),
  ('cashier','cash.shift.read'),
  ('cashier','cash.shift.resume'),
  ('cashier','cash.shift.suspend'),
  ('cashier','catalog.read'),
  ('cashier','checkout.commit'),
  ('cashier','checkout.discount.apply'),
  ('cashier','checkout.terminal.confirm'),
  ('cashier','offline.cash.checkout'),
  ('cashier','offline.replay'),
  ('cashier','sale.exception.history'),
  ('cashier','sale.exception.read'),
  ('cashier','sale.lifecycle'),
  ('cashier','sale.refund.partial'),
  ('manager','cart.write'),
  ('manager','cash.count.recount'),
  ('manager','cash.count.submit'),
  ('manager','cash.drawer.no_sale'),
  ('manager','cash.movement.paid_in'),
  ('manager','cash.movement.paid_in.approve'),
  ('manager','cash.movement.paid_out'),
  ('manager','cash.movement.paid_out.approve'),
  ('manager','cash.movement.safe_drop'),
  ('manager','cash.movement.safe_drop.approve'),
  ('manager','cash.reconcile'),
  ('manager','cash.register.use'),
  ('manager','cash.shift.close'),
  ('manager','cash.shift.close.approve'),
  ('manager','cash.shift.handoff'),
  ('manager','cash.shift.open'),
  ('manager','cash.shift.read'),
  ('manager','cash.shift.resume'),
  ('manager','cash.shift.suspend'),
  ('manager','cash.variance.approve'),
  ('manager','catalog.read'),
  ('manager','checkout.commit'),
  ('manager','checkout.discount.apply'),
  ('manager','checkout.discount.approve'),
  ('manager','checkout.recover.any'),
  ('manager','checkout.terminal.approve'),
  ('manager','checkout.terminal.confirm'),
  ('manager','offline.cash.checkout'),
  ('manager','offline.recovery.review'),
  ('manager','offline.replay'),
  ('manager','sale.exception.history'),
  ('manager','sale.exception.read'),
  ('manager','sale.lifecycle'),
  ('manager','sale.refund.approve'),
  ('manager','sale.refund.cash'),
  ('manager','sale.refund.full'),
  ('manager','sale.refund.manual_terminal'),
  ('manager','sale.refund.other_operator'),
  ('manager','sale.refund.partial'),
  ('manager','sale.refund.reconcile'),
  ('manager','sale.resume.any'),
  ('manager','sale.void.create'),
  ('owner','audit.read'),
  ('owner','cart.write'),
  ('owner','cash.count.recount'),
  ('owner','cash.count.submit'),
  ('owner','cash.drawer.no_sale'),
  ('owner','cash.movement.paid_in'),
  ('owner','cash.movement.paid_in.approve'),
  ('owner','cash.movement.paid_out'),
  ('owner','cash.movement.paid_out.approve'),
  ('owner','cash.movement.safe_drop'),
  ('owner','cash.movement.safe_drop.approve'),
  ('owner','cash.reconcile'),
  ('owner','cash.register.use'),
  ('owner','cash.shift.close'),
  ('owner','cash.shift.close.approve'),
  ('owner','cash.shift.handoff'),
  ('owner','cash.shift.open'),
  ('owner','cash.shift.read'),
  ('owner','cash.shift.resume'),
  ('owner','cash.shift.suspend'),
  ('owner','cash.variance.approve'),
  ('owner','catalog.read'),
  ('owner','checkout.commit'),
  ('owner','checkout.discount.apply'),
  ('owner','checkout.discount.approve'),
  ('owner','checkout.recover.any'),
  ('owner','checkout.terminal.approve'),
  ('owner','checkout.terminal.confirm'),
  ('owner','device.enroll'),
  ('owner','insights.read'),
  ('owner','merchant.manage'),
  ('owner','offline.cash.checkout'),
  ('owner','offline.recovery.review'),
  ('owner','offline.replay'),
  ('owner','sale.exception.history'),
  ('owner','sale.exception.read'),
  ('owner','sale.lifecycle'),
  ('owner','sale.refund.approve'),
  ('owner','sale.refund.cash'),
  ('owner','sale.refund.full'),
  ('owner','sale.refund.manual_terminal'),
  ('owner','sale.refund.other_location'),
  ('owner','sale.refund.other_operator'),
  ('owner','sale.refund.partial'),
  ('owner','sale.refund.reconcile'),
  ('owner','sale.resume.any'),
  ('owner','sale.void.create'),
  ('staff','cart.write'),
  ('staff','cash.count.submit'),
  ('staff','cash.movement.paid_in'),
  ('staff','cash.movement.paid_out'),
  ('staff','cash.movement.safe_drop'),
  ('staff','cash.reconcile'),
  ('staff','cash.register.use'),
  ('staff','cash.shift.close'),
  ('staff','cash.shift.open'),
  ('staff','cash.shift.read'),
  ('staff','cash.shift.resume'),
  ('staff','cash.shift.suspend'),
  ('staff','catalog.read'),
  ('staff','checkout.commit'),
  ('staff','checkout.discount.apply'),
  ('staff','checkout.terminal.confirm'),
  ('staff','offline.cash.checkout'),
  ('staff','offline.replay'),
  ('staff','sale.exception.history'),
  ('staff','sale.exception.read'),
  ('staff','sale.lifecycle'),
  ('staff','sale.refund.partial'),
  ('supervisor','cart.write'),
  ('supervisor','cash.count.recount'),
  ('supervisor','cash.count.submit'),
  ('supervisor','cash.drawer.no_sale'),
  ('supervisor','cash.movement.paid_in'),
  ('supervisor','cash.movement.paid_out'),
  ('supervisor','cash.movement.safe_drop'),
  ('supervisor','cash.reconcile'),
  ('supervisor','cash.register.use'),
  ('supervisor','cash.shift.close'),
  ('supervisor','cash.shift.handoff'),
  ('supervisor','cash.shift.open'),
  ('supervisor','cash.shift.read'),
  ('supervisor','cash.shift.resume'),
  ('supervisor','cash.shift.suspend'),
  ('supervisor','catalog.read'),
  ('supervisor','checkout.commit'),
  ('supervisor','checkout.discount.apply'),
  ('supervisor','checkout.discount.approve'),
  ('supervisor','checkout.recover.any'),
  ('supervisor','checkout.terminal.approve'),
  ('supervisor','checkout.terminal.confirm'),
  ('supervisor','offline.cash.checkout'),
  ('supervisor','offline.replay'),
  ('supervisor','sale.exception.history'),
  ('supervisor','sale.exception.read'),
  ('supervisor','sale.lifecycle'),
  ('supervisor','sale.refund.cash'),
  ('supervisor','sale.refund.full'),
  ('supervisor','sale.refund.manual_terminal'),
  ('supervisor','sale.refund.other_operator'),
  ('supervisor','sale.refund.partial'),
  ('supervisor','sale.refund.reconcile'),
  ('supervisor','sale.resume.any'),
  ('supervisor','sale.void.create'),
  ('viewer','catalog.read'),
  ('viewer','insights.read')
)
insert into umi.role_permission(role_id,permission_id)
select r.id,p.id
from grants g
join umi.role r on r.key=g.role_key and not r.is_platform
join umi.permission p on p.key=g.permission_key
on conflict do nothing;

create or replace function umi.resolve_staff_permissions(p_staff_id uuid)
returns text[]
language sql
stable
security definer
set search_path=umi,merchant,pg_temp
as $$
  select coalesce(array_agg(effective.key order by effective.key),'{}'::text[])
  from (
    select p.key
    from merchant.staff s
    join umi.role_permission rp on rp.role_id=s.role_id
    join umi.permission p on p.id=rp.permission_id
    where s.id=p_staff_id and s.status='active'
      and not exists (
        select 1
        from merchant.staff_permission_override denied
        where denied.staff_id=s.id and denied.permission_id=p.id and denied.effect='deny'
          and (denied.expires_at is null or denied.expires_at>now())
      )
    union
    select p.key
    from merchant.staff_permission_override allowed
    join merchant.staff s on s.id=allowed.staff_id and s.status='active'
    join umi.permission p on p.id=allowed.permission_id
    where allowed.staff_id=p_staff_id and allowed.effect='allow'
      and (allowed.expires_at is null or allowed.expires_at>now())
      and not exists (
        select 1
        from merchant.staff_permission_override denied
        where denied.staff_id=allowed.staff_id
          and denied.permission_id=allowed.permission_id and denied.effect='deny'
          and (denied.expires_at is null or denied.expires_at>now())
      )
  ) effective;
$$;
revoke all on function umi.resolve_staff_permissions(uuid) from public;
grant execute on function umi.resolve_staff_permissions(uuid) to api,worker;

create or replace function runtime.invalidate_operator_sessions_for_rbac()
returns trigger
language plpgsql
security definer
set search_path=runtime,merchant,umi,pg_temp
as $$
begin
  if tg_table_schema='umi' and tg_table_name='role_permission' then
    update runtime.operator_session os
    set state='ended',ended_at=coalesce(ended_at,now()),last_activity_at=now()
    from merchant.staff s
    where os.staff_id=s.id
      and s.role_id=coalesce(new.role_id,old.role_id)
      and os.state in ('active','locked');
  elsif tg_table_schema='merchant' and tg_table_name='staff_permission_override' then
    update runtime.operator_session
    set state='ended',ended_at=coalesce(ended_at,now()),last_activity_at=now()
    where staff_id=coalesce(new.staff_id,old.staff_id)
      and state in ('active','locked');
  else
    update runtime.operator_session
    set state='ended',ended_at=coalesce(ended_at,now()),last_activity_at=now()
    where staff_id=coalesce(new.id,old.id)
      and state in ('active','locked');
  end if;
  return coalesce(new,old);
end $$;

drop trigger if exists role_permission_operator_session_invalidation on umi.role_permission;
create trigger role_permission_operator_session_invalidation
after insert or update or delete on umi.role_permission
for each row execute function runtime.invalidate_operator_sessions_for_rbac();

drop trigger if exists staff_authority_operator_session_invalidation on merchant.staff;
create trigger staff_authority_operator_session_invalidation
after update of role_id,location_id,status on merchant.staff
for each row
when (
  old.role_id is distinct from new.role_id
  or old.location_id is distinct from new.location_id
  or old.status is distinct from new.status
)
execute function runtime.invalidate_operator_sessions_for_rbac();

drop trigger if exists staff_override_operator_session_invalidation
on merchant.staff_permission_override;
create trigger staff_override_operator_session_invalidation
after insert or update or delete on merchant.staff_permission_override
for each row execute function runtime.invalidate_operator_sessions_for_rbac();

-- super_admin stays outside the café matrix. Platform grants use their own authority.

do $$
begin
  if exists (
    select 1
    from (values
  ('admin','audit.read'),
  ('admin','cart.write'),
  ('admin','cash.count.recount'),
  ('admin','cash.count.submit'),
  ('admin','cash.drawer.no_sale'),
  ('admin','cash.movement.paid_in'),
  ('admin','cash.movement.paid_in.approve'),
  ('admin','cash.movement.paid_out'),
  ('admin','cash.movement.paid_out.approve'),
  ('admin','cash.movement.safe_drop'),
  ('admin','cash.movement.safe_drop.approve'),
  ('admin','cash.reconcile'),
  ('admin','cash.register.use'),
  ('admin','cash.shift.close'),
  ('admin','cash.shift.close.approve'),
  ('admin','cash.shift.handoff'),
  ('admin','cash.shift.open'),
  ('admin','cash.shift.read'),
  ('admin','cash.shift.resume'),
  ('admin','cash.shift.suspend'),
  ('admin','cash.variance.approve'),
  ('admin','catalog.read'),
  ('admin','checkout.commit'),
  ('admin','checkout.discount.apply'),
  ('admin','checkout.discount.approve'),
  ('admin','checkout.recover.any'),
  ('admin','checkout.terminal.approve'),
  ('admin','checkout.terminal.confirm'),
  ('admin','device.enroll'),
  ('admin','insights.read'),
  ('admin','merchant.manage'),
  ('admin','offline.cash.checkout'),
  ('admin','offline.recovery.review'),
  ('admin','offline.replay'),
  ('admin','sale.exception.history'),
  ('admin','sale.exception.read'),
  ('admin','sale.lifecycle'),
  ('admin','sale.refund.approve'),
  ('admin','sale.refund.cash'),
  ('admin','sale.refund.full'),
  ('admin','sale.refund.manual_terminal'),
  ('admin','sale.refund.other_operator'),
  ('admin','sale.refund.partial'),
  ('admin','sale.refund.reconcile'),
  ('admin','sale.resume.any'),
  ('admin','sale.void.create'),
  ('cashier','cart.write'),
  ('cashier','cash.count.submit'),
  ('cashier','cash.movement.paid_in'),
  ('cashier','cash.movement.paid_out'),
  ('cashier','cash.movement.safe_drop'),
  ('cashier','cash.reconcile'),
  ('cashier','cash.register.use'),
  ('cashier','cash.shift.close'),
  ('cashier','cash.shift.open'),
  ('cashier','cash.shift.read'),
  ('cashier','cash.shift.resume'),
  ('cashier','cash.shift.suspend'),
  ('cashier','catalog.read'),
  ('cashier','checkout.commit'),
  ('cashier','checkout.discount.apply'),
  ('cashier','checkout.terminal.confirm'),
  ('cashier','offline.cash.checkout'),
  ('cashier','offline.replay'),
  ('cashier','sale.exception.history'),
  ('cashier','sale.exception.read'),
  ('cashier','sale.lifecycle'),
  ('cashier','sale.refund.partial'),
  ('manager','cart.write'),
  ('manager','cash.count.recount'),
  ('manager','cash.count.submit'),
  ('manager','cash.drawer.no_sale'),
  ('manager','cash.movement.paid_in'),
  ('manager','cash.movement.paid_in.approve'),
  ('manager','cash.movement.paid_out'),
  ('manager','cash.movement.paid_out.approve'),
  ('manager','cash.movement.safe_drop'),
  ('manager','cash.movement.safe_drop.approve'),
  ('manager','cash.reconcile'),
  ('manager','cash.register.use'),
  ('manager','cash.shift.close'),
  ('manager','cash.shift.close.approve'),
  ('manager','cash.shift.handoff'),
  ('manager','cash.shift.open'),
  ('manager','cash.shift.read'),
  ('manager','cash.shift.resume'),
  ('manager','cash.shift.suspend'),
  ('manager','cash.variance.approve'),
  ('manager','catalog.read'),
  ('manager','checkout.commit'),
  ('manager','checkout.discount.apply'),
  ('manager','checkout.discount.approve'),
  ('manager','checkout.recover.any'),
  ('manager','checkout.terminal.approve'),
  ('manager','checkout.terminal.confirm'),
  ('manager','offline.cash.checkout'),
  ('manager','offline.recovery.review'),
  ('manager','offline.replay'),
  ('manager','sale.exception.history'),
  ('manager','sale.exception.read'),
  ('manager','sale.lifecycle'),
  ('manager','sale.refund.approve'),
  ('manager','sale.refund.cash'),
  ('manager','sale.refund.full'),
  ('manager','sale.refund.manual_terminal'),
  ('manager','sale.refund.other_operator'),
  ('manager','sale.refund.partial'),
  ('manager','sale.refund.reconcile'),
  ('manager','sale.resume.any'),
  ('manager','sale.void.create'),
  ('owner','audit.read'),
  ('owner','cart.write'),
  ('owner','cash.count.recount'),
  ('owner','cash.count.submit'),
  ('owner','cash.drawer.no_sale'),
  ('owner','cash.movement.paid_in'),
  ('owner','cash.movement.paid_in.approve'),
  ('owner','cash.movement.paid_out'),
  ('owner','cash.movement.paid_out.approve'),
  ('owner','cash.movement.safe_drop'),
  ('owner','cash.movement.safe_drop.approve'),
  ('owner','cash.reconcile'),
  ('owner','cash.register.use'),
  ('owner','cash.shift.close'),
  ('owner','cash.shift.close.approve'),
  ('owner','cash.shift.handoff'),
  ('owner','cash.shift.open'),
  ('owner','cash.shift.read'),
  ('owner','cash.shift.resume'),
  ('owner','cash.shift.suspend'),
  ('owner','cash.variance.approve'),
  ('owner','catalog.read'),
  ('owner','checkout.commit'),
  ('owner','checkout.discount.apply'),
  ('owner','checkout.discount.approve'),
  ('owner','checkout.recover.any'),
  ('owner','checkout.terminal.approve'),
  ('owner','checkout.terminal.confirm'),
  ('owner','device.enroll'),
  ('owner','insights.read'),
  ('owner','merchant.manage'),
  ('owner','offline.cash.checkout'),
  ('owner','offline.recovery.review'),
  ('owner','offline.replay'),
  ('owner','sale.exception.history'),
  ('owner','sale.exception.read'),
  ('owner','sale.lifecycle'),
  ('owner','sale.refund.approve'),
  ('owner','sale.refund.cash'),
  ('owner','sale.refund.full'),
  ('owner','sale.refund.manual_terminal'),
  ('owner','sale.refund.other_location'),
  ('owner','sale.refund.other_operator'),
  ('owner','sale.refund.partial'),
  ('owner','sale.refund.reconcile'),
  ('owner','sale.resume.any'),
  ('owner','sale.void.create'),
  ('staff','cart.write'),
  ('staff','cash.count.submit'),
  ('staff','cash.movement.paid_in'),
  ('staff','cash.movement.paid_out'),
  ('staff','cash.movement.safe_drop'),
  ('staff','cash.reconcile'),
  ('staff','cash.register.use'),
  ('staff','cash.shift.close'),
  ('staff','cash.shift.open'),
  ('staff','cash.shift.read'),
  ('staff','cash.shift.resume'),
  ('staff','cash.shift.suspend'),
  ('staff','catalog.read'),
  ('staff','checkout.commit'),
  ('staff','checkout.discount.apply'),
  ('staff','checkout.terminal.confirm'),
  ('staff','offline.cash.checkout'),
  ('staff','offline.replay'),
  ('staff','sale.exception.history'),
  ('staff','sale.exception.read'),
  ('staff','sale.lifecycle'),
  ('staff','sale.refund.partial'),
  ('supervisor','cart.write'),
  ('supervisor','cash.count.recount'),
  ('supervisor','cash.count.submit'),
  ('supervisor','cash.drawer.no_sale'),
  ('supervisor','cash.movement.paid_in'),
  ('supervisor','cash.movement.paid_out'),
  ('supervisor','cash.movement.safe_drop'),
  ('supervisor','cash.reconcile'),
  ('supervisor','cash.register.use'),
  ('supervisor','cash.shift.close'),
  ('supervisor','cash.shift.handoff'),
  ('supervisor','cash.shift.open'),
  ('supervisor','cash.shift.read'),
  ('supervisor','cash.shift.resume'),
  ('supervisor','cash.shift.suspend'),
  ('supervisor','catalog.read'),
  ('supervisor','checkout.commit'),
  ('supervisor','checkout.discount.apply'),
  ('supervisor','checkout.discount.approve'),
  ('supervisor','checkout.recover.any'),
  ('supervisor','checkout.terminal.approve'),
  ('supervisor','checkout.terminal.confirm'),
  ('supervisor','offline.cash.checkout'),
  ('supervisor','offline.replay'),
  ('supervisor','sale.exception.history'),
  ('supervisor','sale.exception.read'),
  ('supervisor','sale.lifecycle'),
  ('supervisor','sale.refund.cash'),
  ('supervisor','sale.refund.full'),
  ('supervisor','sale.refund.manual_terminal'),
  ('supervisor','sale.refund.other_operator'),
  ('supervisor','sale.refund.partial'),
  ('supervisor','sale.refund.reconcile'),
  ('supervisor','sale.resume.any'),
  ('supervisor','sale.void.create'),
  ('viewer','catalog.read'),
  ('viewer','insights.read')
    ) expected(role_key,permission_key)
    left join umi.role r on r.key=expected.role_key
    left join umi.permission p on p.key=expected.permission_key
    left join umi.role_permission rp on rp.role_id=r.id and rp.permission_id=p.id
    where rp.role_id is null
  ) then
    raise exception 'pilot RBAC grant reconciliation failed';
  end if;
end $$;

commit;
