import type { DashboardOperationDomain } from '@umi/contract';

export interface DashboardDomainPolicy {
  domain: DashboardOperationDomain;
  label: string;
  priority: 'P0' | 'P1' | 'P2';
  administrative: boolean;
  boundary: 'dashboard' | 'pos' | 'kds';
  permissions: string[];
  actions: string[];
  recovery: boolean;
}

export const DASHBOARD_DOMAIN_POLICY: readonly DashboardDomainPolicy[] = [
  {
    domain: 'organization',
    label: 'Organización',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['merchant.manage'],
    actions: ['review', 'edit_settings'],
    recovery: false,
  },
  {
    domain: 'locations',
    label: 'Ubicaciones',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['merchant.manage'],
    actions: ['review', 'edit', 'archive'],
    recovery: false,
  },
  {
    domain: 'memberships',
    label: 'Usuarios y membresías',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['merchant.manage'],
    actions: ['review', 'invite', 'update', 'revoke'],
    recovery: true,
  },
  {
    domain: 'devices',
    label: 'Dispositivos POS',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['device.enroll'],
    actions: ['review', 'enroll', 'approve', 'revoke'],
    recovery: true,
  },
  {
    domain: 'registers',
    label: 'Registros',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['cash.shift.read'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'catalog',
    label: 'Catálogo',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['catalog.read'],
    actions: ['review', 'edit_product', 'archive'],
    recovery: false,
  },
  {
    domain: 'inventory',
    label: 'Inventario',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['inventory.read'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'sales',
    label: 'Ventas',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['sale.lifecycle'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'receipts',
    label: 'Recibos',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['sale.lifecycle'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'refunds_voids',
    label: 'Reembolsos y anulaciones',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['sale.exception.read'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'cash_shifts',
    label: 'Turnos de caja',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['cash.shift.read'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'customers',
    label: 'Clientes',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['customer.read'],
    actions: ['search', 'review', 'merge_preview'],
    recovery: true,
  },
  {
    domain: 'loyalty',
    label: 'Lealtad',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['loyalty.read'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'rewards',
    label: 'Recompensas',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['loyalty.read'],
    actions: ['review', 'configure'],
    recovery: true,
  },
  {
    domain: 'wallet',
    label: 'Wallet',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['wallet.read'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'gift_cards',
    label: 'Gift cards',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['gift_card.read'],
    actions: ['review'],
    recovery: true,
  },
  {
    domain: 'kitchen',
    label: 'Cocina y KDS',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['kitchen.read'],
    actions: ['review', 'stations', 'routes', 'diagnose'],
    recovery: true,
  },
  {
    domain: 'recovery',
    label: 'Centro de recuperación',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['audit.read'],
    actions: ['review', 'copy_reference'],
    recovery: true,
  },
  {
    domain: 'audit',
    label: 'Auditoría',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['audit.read'],
    actions: ['review', 'filter', 'copy_reference'],
    recovery: false,
  },
  {
    domain: 'diagnostics',
    label: 'Diagnóstico',
    priority: 'P0',
    administrative: true,
    boundary: 'dashboard',
    permissions: ['hardware.diagnostics'],
    actions: ['review', 'copy_reference'],
    recovery: true,
  },
] as const;

export function hasDashboardPermission(grants: readonly string[], required: readonly string[]) {
  return grants.includes('*') || required.some((permission) => grants.includes(permission));
}
