import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { zodToJsonSchema } from 'zod-to-json-schema';
import {
  API_MAJOR_VERSION,
  CONTRACT_VERSION,
  errorCatalog,
  invariantCatalog,
  modelCatalog,
  routeCatalog,
} from '../dist/index.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const generated = resolve(root, 'generated');

const stable = (value) => {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([key, item]) => [key, stable(item)]),
    );
  }
  return value;
};

const pointerValue = (rootValue, pointer) =>
  pointer
    .replace(/^#\//, '')
    .split('/')
    .map((part) => part.replaceAll('~1', '/').replaceAll('~0', '~'))
    .reduce((value, part) => value?.[part], rootValue);

const inlineRefs = (value, rootValue, refs = new Set()) => {
  if (Array.isArray(value)) return value.map((item) => inlineRefs(item, rootValue, refs));
  if (!value || typeof value !== 'object') return value;
  if (typeof value.$ref === 'string' && value.$ref.startsWith('#/')) {
    if (refs.has(value.$ref)) throw new Error(`Recursive schema is not supported: ${value.$ref}`);
    const target = pointerValue(rootValue, value.$ref);
    if (!target) throw new Error(`Unresolved schema reference: ${value.$ref}`);
    return inlineRefs(target, rootValue, new Set([...refs, value.$ref]));
  }
  return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [key, inlineRefs(item, rootValue, refs)]),
  );
};

const definitions = {};
for (const [name, schema] of Object.entries(modelCatalog).sort(([a], [b]) => a.localeCompare(b))) {
  const json = zodToJsonSchema(schema, { name, $refStrategy: 'root' });
  definitions[name] = inlineRefs(json.definitions?.[name] ?? json, json);
}

const payload = stable({
  manifestVersion: 1,
  contractVersion: CONTRACT_VERSION,
  apiMajorVersion: API_MAJOR_VERSION,
  definitions,
  errors: errorCatalog,
  invariants: invariantCatalog,
  routes: routeCatalog,
  security: {
    internalIdsExposed: false,
    serviceRoleExposed: false,
    tenantContextRequiredForTenantRoutes: true,
    branchContextValidatedByApi: true,
  },
});
const canonical = `${JSON.stringify(payload, null, 2)}\n`;
const contentHash = createHash('sha256').update(canonical).digest('hex');
const artifact = `${JSON.stringify(stable({ ...payload, contentHash }), null, 2)}\n`;
const artifactHash = createHash('sha256').update(artifact).digest('hex');

const nullable = (schema) =>
  schema?.anyOf?.some((item) => item.type === 'null') ||
  (Array.isArray(schema?.type) && schema.type.includes('null'));
const withoutNull = (schema) =>
  schema?.anyOf?.find((item) => item.type !== 'null') ??
  (Array.isArray(schema?.type)
    ? { ...schema, type: schema.type.find((item) => item !== 'null') }
    : schema);

function tsType(input) {
  const schema = withoutNull(input);
  let value = 'unknown';
  if (schema?.enum) value = schema.enum.map((item) => JSON.stringify(item)).join(' | ');
  else if (schema?.type === 'string') value = 'string';
  else if (schema?.type === 'integer' || schema?.type === 'number') value = 'number';
  else if (schema?.type === 'boolean') value = 'boolean';
  else if (schema?.type === 'array') value = `Array<${tsType(schema.items)}>`;
  else if (schema?.type === 'object' && schema.additionalProperties) {
    value = `Record<string, ${tsType(schema.additionalProperties)}>`;
  } else if (schema?.type === 'object') {
    const required = new Set(schema.required ?? []);
    value = `{ ${Object.entries(schema.properties ?? {})
      .map(
        ([key, item]) => `${JSON.stringify(key)}${required.has(key) ? '' : '?'}: ${tsType(item)}`,
      )
      .join('; ')} }`;
  }
  return nullable(input) ? `${value} | null` : value;
}

const tsModels = Object.entries(definitions)
  .map(([name, schema]) => `export type ${name} = ${tsType(schema)};`)
  .join('\n\n');
const tsOutput =
  `// Generated by packages/contract/scripts/generate.mjs. Do not edit.\n` +
  `export const contractVersion = ${JSON.stringify(CONTRACT_VERSION)} as const;\n` +
  `export const contractContentHash = ${JSON.stringify(contentHash)} as const;\n\n${tsModels}\n`;

function dartType(input) {
  const schema = withoutNull(input);
  let value = 'Object?';
  if (schema?.type === 'string' || schema?.enum) value = 'String';
  else if (schema?.type === 'integer') value = 'int';
  else if (schema?.type === 'number') value = 'num';
  else if (schema?.type === 'boolean') value = 'bool';
  else if (schema?.type === 'array') value = `List<${dartType(schema.items).replace(/\?$/, '')}>`;
  else if (schema?.type === 'object') value = 'Map<String, Object?>';
  return nullable(input) ? `${value.replace(/\?$/, '')}?` : value;
}

function dartDecode(input, expression) {
  const schema = withoutNull(input);
  const optional = nullable(input);
  const wrap = (value) => (optional ? `${expression} == null ? null : ${value}` : value);
  if (schema?.type === 'array') {
    const type = dartType(schema.items).replace(/\?$/, '');
    return wrap(`(${expression} as List<Object?>).cast<${type}>()`);
  }
  if (schema?.type === 'integer') return wrap(`(${expression} as num).toInt()`);
  if (schema?.type === 'number') return wrap(`${expression} as num`);
  if (schema?.type === 'boolean') return wrap(`${expression} as bool`);
  if (schema?.type === 'string' || schema?.enum) return wrap(`${expression} as String`);
  if (schema?.type === 'object') return wrap(`${expression} as Map<String, Object?>`);
  return expression;
}

function dartEncode(input, expression) {
  const schema = withoutNull(input);
  return expression;
}

function dartClass(name, schema) {
  if (schema.type !== 'object' || schema.additionalProperties) {
    return `typedef ${name} = ${dartType(schema)};`;
  }
  const properties = Object.entries(schema.properties ?? {});
  const required = new Set(schema.required ?? []);
  const fieldType = (key, value) => {
    const type = dartType(value);
    return required.has(key) || type.endsWith('?') ? type : `${type.replace(/\?$/, '')}?`;
  };
  const fields = properties
    .map(([key, value]) => `  final ${fieldType(key, value)} ${key};`)
    .join('\n');
  const parameters = properties
    .map(([key]) => `    ${required.has(key) ? 'required ' : ''}this.${key},`)
    .join('\n');
  const decode = properties
    .map(([key, value]) => {
      const input =
        required.has(key) || nullable(value) ? value : { anyOf: [value, { type: 'null' }] };
      return `      ${key}: ${dartDecode(input, `json[${JSON.stringify(key)}]`)},`;
    })
    .join('\n');
  const encode = properties
    .map(([key, value]) => `      ${JSON.stringify(key)}: ${dartEncode(value, key)},`)
    .join('\n');
  return `final class ${name} {
${fields}

  const ${name}({
${parameters}
  });

  factory ${name}.fromJson(Map<String, Object?> json) => ${name}(
${decode}
  );

  Map<String, Object?> toJson() => {
${encode}
  };
}`;
}

const dartModels = Object.entries(definitions)
  .map(([name, schema]) => dartClass(name, schema))
  .join('\n\n');
const dartRoutes = `abstract final class UmiRoutes {
  static const deviceEnrollmentComplete = '/api/devices/enrollment/complete';
  static const deviceStatus = '/api/devices/status';
  static const posLogin = '/api/auth/pos/login';
  static const posRefresh = '/api/auth/pos/refresh';
  static const posLogout = '/api/auth/pos/logout';
  static const globalLogout = '/api/auth/local/global-logout';
  static const posEntryContext = '/api/pos/entry-context';
  static const operatorSessions = '/api/pos/operator-sessions';
  static const operatorPin = '/api/pos/elevation/pin';
  static const managerApproval = '/api/pos/elevation/manager-approval';

  static String operatorLock(String id) =>
      '/api/pos/operator-sessions/\${Uri.encodeComponent(id)}/lock';
  static String operatorEnd(String id) =>
      '/api/pos/operator-sessions/\${Uri.encodeComponent(id)}/end';
  static String posCatalogCategories(String tenantId) =>
      '/api/pos/tenants/\${Uri.encodeComponent(tenantId)}/catalog/categories';
  static String posCatalogProducts(String tenantId) =>
      '/api/pos/tenants/\${Uri.encodeComponent(tenantId)}/catalog/products';
  static String posCatalogProduct(String tenantId, String productId) =>
      '/api/pos/tenants/\${Uri.encodeComponent(tenantId)}/catalog/products/\${Uri.encodeComponent(productId)}';
  static String posCart(String tenantId) =>
      '/api/pos/tenants/\${Uri.encodeComponent(tenantId)}/cart';
  static String posCartLines(String tenantId) =>
      '/api/pos/tenants/\${Uri.encodeComponent(tenantId)}/cart/lines';
  static String posCartLine(String tenantId, String lineId) =>
      '/api/pos/tenants/\${Uri.encodeComponent(tenantId)}/cart/lines/\${Uri.encodeComponent(lineId)}';
  static String posCartPrepare(String tenantId) =>
      '/api/pos/tenants/\${Uri.encodeComponent(tenantId)}/cart/prepare';
}`;
const dartOutput =
  `// Generated by packages/contract/scripts/generate.mjs. Do not edit.\n` +
  `const String contractVersion = ${JSON.stringify(CONTRACT_VERSION)};\n` +
  `const String contractContentHash = ${JSON.stringify(contentHash)};\n\n` +
  `${dartRoutes}\n\n${dartModels}\n`;

const outputs = {
  'contract.json': artifact,
  'contract.sha256': `${artifactHash}  contract.json\n`,
  'typescript/umi_contract.ts': tsOutput,
  'dart/lib/umi_contract.dart': dartOutput,
  'dart/pubspec.yaml':
    'name: umi_contract\\ndescription: Generated UMI API contract models.\\nversion: 1.0.0\\nenvironment:\\n  sdk: \">=3.4.0 <4.0.0\"\\n',
};

// Keep package metadata consumable by Dart pub. The historical template above
// encoded backslash-n pairs; override it with deterministic real YAML lines.
outputs['dart/pubspec.yaml'] = `${[
  'name: umi_contract',
  'description: Generated UMI API contract models.',
  `version: ${CONTRACT_VERSION}`,
  'environment:',
  '  sdk: ">=3.4.0 <4.0.0"',
].join('\n')}\n`;

if (process.argv.includes('--check')) {
  for (const [path, contents] of Object.entries(outputs)) {
    const actual = await readFile(resolve(generated, path), 'utf8').catch(() => '');
    if (actual !== contents) throw new Error(`Generated contract drift: ${path}`);
  }
} else {
  for (const [path, contents] of Object.entries(outputs)) {
    const target = resolve(generated, path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, contents);
  }
}

process.stdout.write(`Generated UMI contract ${CONTRACT_VERSION} (${contentHash})\n`);
