import { API_ERROR_CODES, contractModels } from './platform';
import { httpModels } from './schemas';
import { deviceModels } from './device';
import { posCatalogModels } from './pos-catalog';
import { posCartModels } from './pos-cart';

export const CONTRACT_VERSION = '1.3.0';
export const API_MAJOR_VERSION = 1;

export const errorCatalog = Object.fromEntries(
  API_ERROR_CODES.map((code) => [
    code,
    {
      public: true,
      retryable:
        code === 'RATE_LIMITED' || code === 'INTERNAL_ERROR' || code === 'PAYMENT_OUTCOME_UNKNOWN',
    },
  ]),
);

export const routeCatalog = {
  'POST /api/auth/local/login': {
    request: 'LoginRequest',
    response: 'SessionResponse',
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'AUTHENTICATION_REQUIRED', 'RATE_LIMITED'],
  },
  'POST /api/auth/local/refresh': {
    request: null,
    response: 'SessionResponse',
    auth: 'refresh-cookie',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED', 'RATE_LIMITED'],
  },
  'POST /api/auth/local/logout': {
    request: null,
    response: 'OkResponse',
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: [],
  },
  'POST /api/auth/local/global-logout': {
    request: 'GlobalLogoutRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED'],
  },
  'POST /api/auth/local/forgot-password': {
    request: 'ForgotPasswordRequest',
    response: 'OkResponse',
    auth: 'public',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'RATE_LIMITED'],
  },
  'POST /api/auth/local/reset-password': {
    request: 'ResetPasswordRequest',
    response: 'OkResponse',
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'AUTHENTICATION_REQUIRED', 'RATE_LIMITED'],
  },
  'GET /api/auth/me': {
    request: null,
    response: 'SessionResponse',
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED'],
  },
  'GET /api/me/tenants': {
    request: null,
    response: 'MeTenantsResponse',
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED'],
  },
  'POST /api/tenants/:tenantId/devices/enrollment': {
    request: 'BeginDeviceEnrollmentRequest',
    response: 'EnrollmentChallenge',
    auth: 'session',
    permission: 'devices.manage',
    idempotent: true,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'BRANCH_NOT_FOUND', 'RATE_LIMITED'],
  },
  'POST /api/devices/enrollment/complete': {
    request: 'CompleteDeviceEnrollmentRequest',
    response: 'DeviceCredentialEnvelope',
    auth: 'enrollment-challenge',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['ENROLLMENT_EXPIRED', 'ENROLLMENT_REJECTED', 'ENROLLMENT_ATTEMPTS_EXCEEDED'],
  },
  'GET /api/devices/status': {
    request: null,
    response: 'DeviceSummary',
    auth: 'device-credential',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['DEVICE_CREDENTIAL_INVALID', 'DEVICE_REVOKED'],
  },
  'POST /api/auth/pos/login': {
    request: 'PosLoginRequest',
    response: 'PosSessionResponse',
    auth: 'device-credential',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED', 'DEVICE_NOT_ALLOWED', 'RATE_LIMITED'],
  },
  'POST /api/auth/pos/refresh': {
    request: 'PosRefreshRequest',
    response: 'PosSessionResponse',
    auth: 'device-credential',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['SESSION_REVOKED', 'DEVICE_NOT_ALLOWED', 'RATE_LIMITED'],
  },
  'GET /api/pos/entry-context': {
    request: null,
    response: null,
    auth: 'device-session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED', 'DEVICE_REVOKED'],
  },
  'POST /api/pos/operator-sessions': {
    request: 'StartOperatorSessionRequest',
    response: 'OperatorSessionView',
    auth: 'device-session',
    permission: null,
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['BRANCH_NOT_FOUND', 'PERMISSION_DENIED', 'DEVICE_REVOKED'],
  },
  'POST /api/pos/elevation/pin': {
    request: 'VerifyOperatorPinRequest',
    response: 'ElevationGrantView',
    auth: 'device-session',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: true,
    approval: false,
    errors: ['PERMISSION_DENIED', 'PIN_LOCKED', 'RATE_LIMITED'],
  },
  'POST /api/pos/elevation/manager-approval': {
    request: 'ManagerApprovalRequest',
    response: 'ElevationGrantView',
    auth: 'device-session',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: true,
    approval: true,
    errors: ['PERMISSION_DENIED', 'PIN_LOCKED', 'RATE_LIMITED'],
  },
  'POST /api/:slug/admin/staff': {
    request: 'CreateStaffRequest',
    response: null,
    auth: 'session',
    permission: 'staff.manage',
    idempotent: false,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'TENANT_NOT_FOUND', 'BRANCH_NOT_FOUND'],
  },
  'PATCH /api/:slug/admin/staff/:staffId': {
    request: 'UpdateStaffRequest',
    response: null,
    auth: 'session',
    permission: 'staff.manage',
    idempotent: false,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'RESOURCE_NOT_FOUND'],
  },
  'POST /api/:slug/admin/scan': {
    request: 'ScanRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'TENANT_NOT_FOUND'],
  },
  'POST /api/:slug/admin/topup': {
    request: 'TopupRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'IDEMPOTENCY_CONFLICT'],
  },
  'POST /api/:slug/admin/purchase': {
    request: 'PurchaseRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'IDEMPOTENCY_CONFLICT'],
  },
  'POST /api/:slug/admin/gift-cards': {
    request: 'GiftCardCreateRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'RATE_LIMITED'],
  },
  'POST /api/:slug/customers': {
    request: 'RegisterMemberRequest',
    response: null,
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'CONFLICT', 'RATE_LIMITED'],
  },
  'POST /api/:slug/gift/:code': {
    request: 'GiftRedeemRequest',
    response: null,
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'RESOURCE_NOT_FOUND', 'RATE_LIMITED'],
  },
  'GET /api/pos/tenants/:tenantId/catalog/categories': {
    request: 'CatalogQuery',
    response: 'CatalogCategoriesResponse',
    auth: 'operator-session',
    permission: 'catalog.read',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'BRANCH_NOT_FOUND', 'FEATURE_UNAVAILABLE'],
  },
  'GET /api/pos/tenants/:tenantId/catalog/products': {
    request: 'CatalogQuery',
    response: 'CatalogPage',
    auth: 'operator-session',
    permission: 'catalog.read',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'BRANCH_NOT_FOUND', 'FEATURE_UNAVAILABLE'],
  },
  'GET /api/pos/tenants/:tenantId/catalog/products/:productId': {
    request: 'CatalogQuery',
    response: 'CatalogProductDetail',
    auth: 'operator-session',
    permission: 'catalog.read',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'BRANCH_NOT_FOUND', 'RESOURCE_NOT_FOUND'],
  },
  'POST /api/pos/tenants/:tenantId/cart': {
    request: 'CreateCartRequest',
    response: 'Cart',
    auth: 'operator-session',
    permission: 'cart.write',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'BRANCH_NOT_FOUND', 'IDEMPOTENCY_CONFLICT'],
  },
  'GET /api/pos/tenants/:tenantId/cart': {
    request: 'CartQuery',
    response: 'Cart',
    auth: 'operator-session',
    permission: 'cart.write',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'RESOURCE_NOT_FOUND'],
  },
  'POST /api/pos/tenants/:tenantId/cart/lines': {
    request: 'CartLineInput',
    response: 'Cart',
    auth: 'operator-session',
    permission: 'cart.write',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'CART_VALIDATION_FAILED', 'IDEMPOTENCY_CONFLICT'],
  },
  'PATCH /api/pos/tenants/:tenantId/cart/lines/:lineId': {
    request: 'CartLineInput',
    response: 'Cart',
    auth: 'operator-session',
    permission: 'cart.write',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'CART_VALIDATION_FAILED', 'OPTIMISTIC_VERSION_CONFLICT'],
  },
  'DELETE /api/pos/tenants/:tenantId/cart/lines/:lineId': {
    request: 'RemoveCartLineRequest',
    response: 'Cart',
    auth: 'operator-session',
    permission: 'cart.write',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'OPTIMISTIC_VERSION_CONFLICT'],
  },
  'POST /api/pos/tenants/:tenantId/cart/prepare': {
    request: 'PrepareSaleRequest',
    response: 'Cart',
    auth: 'operator-session',
    permission: 'cart.write',
    idempotent: true,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['PERMISSION_DENIED', 'CART_VALIDATION_FAILED', 'OPTIMISTIC_VERSION_CONFLICT'],
  },
} as const;

export const modelCatalog = {
  ...httpModels,
  ...contractModels,
  ...deviceModels,
  ...posCatalogModels,
  ...posCartModels,
};

export const invariantCatalog = {
  PaymentAmbiguity:
    'When status is unknown, queryOnly must be true and canRetryAsNew must be false.',
  Money: 'minorUnits is an integer and currency is an uppercase ISO 4217 code.',
  OfflineCommandEnvelope: 'sequence is positive and fingerprint is a SHA-256 hexadecimal value.',
} as const;
