import { API_ERROR_CODES, contractModels } from './platform';
import { httpModels } from './schemas';

export const CONTRACT_VERSION = '1.0.0';
export const API_MAJOR_VERSION = 1;

export const errorCatalog = Object.fromEntries(
  API_ERROR_CODES.map((code) => [
    code,
    {
      public: true,
      retryable:
        code === 'RATE_LIMITED' || code === 'INTERNAL_ERROR' || code === 'PAYMENT_OUTCOME_UNKNOWN',
    },
  ]),
);

export const routeCatalog = {
  'POST /api/auth/local/login': {
    request: 'LoginRequest',
    response: 'SessionResponse',
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'AUTHENTICATION_REQUIRED', 'RATE_LIMITED'],
  },
  'POST /api/auth/local/refresh': {
    request: null,
    response: 'SessionResponse',
    auth: 'refresh-cookie',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED', 'RATE_LIMITED'],
  },
  'POST /api/auth/local/logout': {
    request: null,
    response: 'OkResponse',
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: [],
  },
  'POST /api/auth/local/global-logout': {
    request: 'GlobalLogoutRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED'],
  },
  'POST /api/auth/local/forgot-password': {
    request: 'ForgotPasswordRequest',
    response: 'OkResponse',
    auth: 'public',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'RATE_LIMITED'],
  },
  'POST /api/auth/local/reset-password': {
    request: 'ResetPasswordRequest',
    response: 'OkResponse',
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'AUTHENTICATION_REQUIRED', 'RATE_LIMITED'],
  },
  'GET /api/auth/me': {
    request: null,
    response: 'SessionResponse',
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED'],
  },
  'GET /api/me/tenants': {
    request: null,
    response: 'MeTenantsResponse',
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: false,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['AUTHENTICATION_REQUIRED'],
  },
  'POST /api/:slug/admin/staff': {
    request: 'CreateStaffRequest',
    response: null,
    auth: 'session',
    permission: 'staff.manage',
    idempotent: false,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'TENANT_NOT_FOUND', 'BRANCH_NOT_FOUND'],
  },
  'PATCH /api/:slug/admin/staff/:staffId': {
    request: 'UpdateStaffRequest',
    response: null,
    auth: 'session',
    permission: 'staff.manage',
    idempotent: false,
    tenantContext: true,
    branchContext: true,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'RESOURCE_NOT_FOUND'],
  },
  'POST /api/:slug/admin/scan': {
    request: 'ScanRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'TENANT_NOT_FOUND'],
  },
  'POST /api/:slug/admin/topup': {
    request: 'TopupRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'IDEMPOTENCY_CONFLICT'],
  },
  'POST /api/:slug/admin/purchase': {
    request: 'PurchaseRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: true,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'IDEMPOTENCY_CONFLICT'],
  },
  'POST /api/:slug/admin/gift-cards': {
    request: 'GiftCardCreateRequest',
    response: null,
    auth: 'session',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'PERMISSION_DENIED', 'RATE_LIMITED'],
  },
  'POST /api/:slug/customers': {
    request: 'RegisterMemberRequest',
    response: null,
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'CONFLICT', 'RATE_LIMITED'],
  },
  'POST /api/:slug/gift/:code': {
    request: 'GiftRedeemRequest',
    response: null,
    auth: 'public',
    permission: null,
    idempotent: false,
    tenantContext: true,
    branchContext: false,
    offline: false,
    pin: false,
    approval: false,
    errors: ['VALIDATION_FAILED', 'RESOURCE_NOT_FOUND', 'RATE_LIMITED'],
  },
} as const;

export const modelCatalog = { ...httpModels, ...contractModels };

export const invariantCatalog = {
  PaymentAmbiguity:
    'When status is unknown, queryOnly must be true and canRetryAsNew must be false.',
  Money: 'minorUnits is an integer and currency is an uppercase ISO 4217 code.',
  OfflineCommandEnvelope: 'sequence is positive and fingerprint is a SHA-256 hexadecimal value.',
} as const;
